/*
 * ecpp_gpu_driver.cpp — CUDA Driver API host driver for ECPP kernels
 *
 * Uses the CUDA Driver API loaded dynamically at runtime via cuda_loader.h.
 * No CUDA SDK needed at build or run time — only nvcuda.dll.
 *
 * PTX kernels are embedded as string constants (generated by nvcc offline)
 * and JIT-compiled by the driver to the user's specific GPU architecture.
 *
 * Build: compiled as plain C++ (g++, clang++, MSVC) — no nvcc required.
 *
 * Copyright (c) 2026 The Freycoin developers
 * Licensed under GPL v3+
 */

#include <pow/gpu_accel/ecpp_gpu_driver.h>
#include <gpu/cuda_loader.h>

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

/* =========================================================================
 * Embedded CUBIN (pre-compiled for sm_89, linked via objcopy)
 * ========================================================================= */

extern "C" {
    extern const unsigned char _binary_ecpp_tonelli_fatbin_start[];
    extern const unsigned char _binary_ecpp_tonelli_fatbin_end[];
    extern const unsigned char _binary_ecpp_cornacchia_fatbin_start[];
    extern const unsigned char _binary_ecpp_cornacchia_fatbin_end[];
    extern const unsigned char _binary_ecpp_bpsw_fatbin_start[];
    extern const unsigned char _binary_ecpp_bpsw_fatbin_end[];
    extern const unsigned char _binary_ecpp_ec_fatbin_start[];
    extern const unsigned char _binary_ecpp_ec_fatbin_end[];
}

/* =========================================================================
 * Embedded PTX sources (fallback for non-sm_89 GPUs)
 * ========================================================================= */

static const char* tonelli_ptx_source =
#include "ecpp_tonelli_ptx_source.h"
;

static const char* cornacchia_ptx_source =
#include "ecpp_cornacchia_ptx_source.h"
;

static const char* bpsw_ptx_source =
#include "ecpp_bpsw_ptx_source.h"
;

static const char* ec_ptx_source =
#include "ecpp_ec_ptx_source.h"
;

/* =========================================================================
 * CGBN kernel block size (must match the kernel thread organization)
 * ========================================================================= */

#define ECPP_BLOCK_SIZE 128

/* =========================================================================
 * Global CUDA state
 * ========================================================================= */

static CUdevice   g_device = -1;
static CUcontext  g_context = nullptr;
static int        g_initialized = 0;
static char       g_device_name[256] = {0};
static uint64_t   g_device_memory = 0;

/* ─── Kernel tier info (shared structure) ───────────────────────────── */

struct KernelTierInfo {
    int bits;
    int tpi;
    const char* kernel_name;
    CUfunction kernel;
};

/* ─── Tonelli-Shanks module ──────────────────────────────────────────── */

static CUmodule g_tonelli_module = nullptr;

static KernelTierInfo g_tonelli_tiers[] = {
    {   320,  8, "ecpp_tonelli_kernel_320",   nullptr},
    {   384, 16, "ecpp_tonelli_kernel_384",   nullptr},
    {   512, 16, "ecpp_tonelli_kernel_512",   nullptr},
    {  1024, 32, "ecpp_tonelli_kernel_1024",  nullptr},
    {  1280, 32, "ecpp_tonelli_kernel_1280",  nullptr},
    {  2048, 32, "ecpp_tonelli_kernel_2048",  nullptr},
    {  4096, 32, "ecpp_tonelli_kernel_4096",  nullptr},
    {  8192, 32, "ecpp_tonelli_kernel_8192",  nullptr},
    {  8448, 32, "ecpp_tonelli_kernel_8448",  nullptr},
    { 12288, 32, "ecpp_tonelli_kernel_12288", nullptr},
    { 16384, 32, "ecpp_tonelli_kernel_16384", nullptr},
    { 16640, 32, "ecpp_tonelli_kernel_16640", nullptr},
};
static const int g_tonelli_num_tiers = sizeof(g_tonelli_tiers) / sizeof(g_tonelli_tiers[0]);

/* ─── Cornacchia module ──────────────────────────────────────────────── */

static CUmodule g_cornacchia_module = nullptr;

static KernelTierInfo g_cornacchia_tiers[] = {
    {   320,  8, "ecpp_cornacchia_kernel_320",   nullptr},
    {   384, 16, "ecpp_cornacchia_kernel_384",   nullptr},
    {   512, 16, "ecpp_cornacchia_kernel_512",   nullptr},
    {  1024, 32, "ecpp_cornacchia_kernel_1024",  nullptr},
    {  1280, 32, "ecpp_cornacchia_kernel_1280",  nullptr},
    {  2048, 32, "ecpp_cornacchia_kernel_2048",  nullptr},
    {  4096, 32, "ecpp_cornacchia_kernel_4096",  nullptr},
    {  8192, 32, "ecpp_cornacchia_kernel_8192",  nullptr},
    {  8448, 32, "ecpp_cornacchia_kernel_8448",  nullptr},
    { 12288, 32, "ecpp_cornacchia_kernel_12288", nullptr},
    { 16384, 32, "ecpp_cornacchia_kernel_16384", nullptr},
    { 16640, 32, "ecpp_cornacchia_kernel_16640", nullptr},
};
static const int g_cornacchia_num_tiers = sizeof(g_cornacchia_tiers) / sizeof(g_cornacchia_tiers[0]);

/* ─── BPSW module ────────────────────────────────────────────────────── */

static CUmodule g_bpsw_module = nullptr;

static KernelTierInfo g_bpsw_tiers[] = {
    {   320,  8, "ecpp_bpsw_kernel_320",   nullptr},
    {   384, 16, "ecpp_bpsw_kernel_384",   nullptr},
    {   512, 16, "ecpp_bpsw_kernel_512",   nullptr},
    {  1024, 32, "ecpp_bpsw_kernel_1024",  nullptr},
    {  1280, 32, "ecpp_bpsw_kernel_1280",  nullptr},
    {  2048, 32, "ecpp_bpsw_kernel_2048",  nullptr},
    {  4096, 32, "ecpp_bpsw_kernel_4096",  nullptr},
    {  8192, 32, "ecpp_bpsw_kernel_8192",  nullptr},
    {  8448, 32, "ecpp_bpsw_kernel_8448",  nullptr},
    { 12288, 32, "ecpp_bpsw_kernel_12288", nullptr},
    { 16384, 32, "ecpp_bpsw_kernel_16384", nullptr},
    { 16640, 32, "ecpp_bpsw_kernel_16640", nullptr},
};
static const int g_bpsw_num_tiers = sizeof(g_bpsw_tiers) / sizeof(g_bpsw_tiers[0]);

/* ─── EC module ──────────────────────────────────────────────────────── */

static CUmodule g_ec_module = nullptr;

static KernelTierInfo g_ec_tiers[] = {
    {   320,  8, "ecpp_ec_kernel_320",   nullptr},
    {   384, 16, "ecpp_ec_kernel_384",   nullptr},
    {   512, 16, "ecpp_ec_kernel_512",   nullptr},
    {  1024, 32, "ecpp_ec_kernel_1024",  nullptr},
    {  1280, 32, "ecpp_ec_kernel_1280",  nullptr},
    {  2048, 32, "ecpp_ec_kernel_2048",  nullptr},
    {  4096, 32, "ecpp_ec_kernel_4096",  nullptr},
    {  8192, 32, "ecpp_ec_kernel_8192",  nullptr},
    {  8448, 32, "ecpp_ec_kernel_8448",  nullptr},
    { 12288, 32, "ecpp_ec_kernel_12288", nullptr},
    { 16384, 32, "ecpp_ec_kernel_16384", nullptr},
    { 16640, 32, "ecpp_ec_kernel_16640", nullptr},
};
static const int g_ec_num_tiers = sizeof(g_ec_tiers) / sizeof(g_ec_tiers[0]);

/* =========================================================================
 * Helper: resolve all tier kernels from a loaded module
 * ========================================================================= */

static int resolve_kernels(CUmodule mod, KernelTierInfo *tiers, int num_tiers,
                           const char *label)
{
    for (int i = 0; i < num_tiers; i++) {
        CUresult res = cu_cuModuleGetFunction(&tiers[i].kernel, mod, tiers[i].kernel_name);
        if (res != CUDA_SUCCESS) {
            fprintf(stderr, "ECPP GPU: Failed to find kernel '%s' in %s module (error %d)\n",
                    tiers[i].kernel_name, label, res);
            return -1;
        }
    }
    return 0;
}

/* =========================================================================
 * Helper: load CUBIN (pre-compiled) or fall back to PTX JIT
 * ========================================================================= */

static int load_module(CUmodule *mod, KernelTierInfo *tiers, int num_tiers,
                       const unsigned char *cubin_data, unsigned int cubin_size,
                       const char *ptx_source, const char *label)
{
    CUresult res;

    /* Try pre-compiled CUBIN first (instant load, no JIT) */
    res = cu_cuModuleLoadData(mod, cubin_data);
    if (res == CUDA_SUCCESS) {
        if (resolve_kernels(*mod, tiers, num_tiers, label) == 0) {
            fprintf(stderr, "ECPP GPU: Loaded pre-compiled %s CUBIN\n", label);
            return 0;
        }
        cu_cuModuleUnload(*mod);
        *mod = nullptr;
    }

    /* Fall back to JIT-compiling PTX (slower, but works on any GPU arch) */
    fprintf(stderr, "ECPP GPU: JIT-compiling %s PTX (CUBIN not compatible)...\n", label);

    char jit_error_log[4096] = {0};
    char jit_info_log[4096] = {0};
    CUjit_option jit_options[] = {
        CU_JIT_ERROR_LOG_BUFFER,
        CU_JIT_ERROR_LOG_BUFFER_SIZE_BYTES,
        CU_JIT_INFO_LOG_BUFFER,
        CU_JIT_INFO_LOG_BUFFER_SIZE_BYTES,
    };
    void* jit_option_values[] = {
        (void*)jit_error_log,
        (void*)(size_t)sizeof(jit_error_log),
        (void*)jit_info_log,
        (void*)(size_t)sizeof(jit_info_log),
    };

    res = cu_cuModuleLoadDataEx(mod, ptx_source, 4, jit_options, jit_option_values);
    if (res != CUDA_SUCCESS) {
        fprintf(stderr, "ECPP GPU: Failed to JIT-compile %s PTX (error %d)\n", label, res);
        if (jit_error_log[0])
            fprintf(stderr, "JIT error:\n%s\n", jit_error_log);
        return -1;
    }

    if (resolve_kernels(*mod, tiers, num_tiers, label) != 0) {
        cu_cuModuleUnload(*mod);
        *mod = nullptr;
        return -1;
    }

    return 0;
}

/* =========================================================================
 * Initialization
 * ========================================================================= */

int ecpp_gpu_init(int device_id)
{
    CUresult res;

    if (g_initialized) return 0;

    /* Load CUDA Driver API dynamically */
    if (!cuda_is_loaded()) {
        if (cuda_load() != 0) {
            fprintf(stderr, "ECPP GPU: CUDA driver not available\n");
            return -2;
        }
    }

    /* Device count */
    int device_count = 0;
    res = cu_cuDeviceGetCount(&device_count);
    if (res != CUDA_SUCCESS || device_count == 0) {
        fprintf(stderr, "ECPP GPU: No CUDA devices found\n");
        return -2;
    }
    if (device_id >= device_count) device_id = 0;

    /* Get device */
    res = cu_cuDeviceGet(&g_device, device_id);
    if (res != CUDA_SUCCESS) return -1;

    cu_cuDeviceGetName(g_device_name, sizeof(g_device_name), g_device);
    size_t mem = 0;
    cu_cuDeviceTotalMem(&mem, g_device);
    g_device_memory = mem;

    /* Check compute capability (need 7.5+ for our PTX target) */
    int cc_major = 0, cc_minor = 0;
    cu_cuDeviceGetAttribute(&cc_major, CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MAJOR, g_device);
    cu_cuDeviceGetAttribute(&cc_minor, CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MINOR, g_device);
    if (cc_major < 7 || (cc_major == 7 && cc_minor < 5)) {
        fprintf(stderr, "ECPP GPU: Compute capability %d.%d too old (need 7.5+ / Turing)\n",
                cc_major, cc_minor);
        return -2;
    }

    /* Create context */
    res = cu_cuCtxCreate(&g_context, 0, g_device);
    if (res != CUDA_SUCCESS) {
        fprintf(stderr, "ECPP GPU: Failed to create CUDA context (error %d)\n", res);
        return -1;
    }

    /* Load Tonelli-Shanks (CUBIN → PTX fallback) */
    if (load_module(&g_tonelli_module, g_tonelli_tiers, g_tonelli_num_tiers,
                    _binary_ecpp_tonelli_fatbin_start,
                    (unsigned int)(_binary_ecpp_tonelli_fatbin_end - _binary_ecpp_tonelli_fatbin_start),
                    tonelli_ptx_source, "Tonelli-Shanks") != 0) {
        cu_cuCtxDestroy(g_context);
        g_context = nullptr;
        return -1;
    }

    /* Load Cornacchia (CUBIN → PTX fallback) */
    if (load_module(&g_cornacchia_module, g_cornacchia_tiers, g_cornacchia_num_tiers,
                    _binary_ecpp_cornacchia_fatbin_start,
                    (unsigned int)(_binary_ecpp_cornacchia_fatbin_end - _binary_ecpp_cornacchia_fatbin_start),
                    cornacchia_ptx_source, "Cornacchia") != 0) {
        cu_cuModuleUnload(g_tonelli_module);
        g_tonelli_module = nullptr;
        cu_cuCtxDestroy(g_context);
        g_context = nullptr;
        return -1;
    }

    /* Load BPSW (CUBIN → PTX fallback) */
    if (load_module(&g_bpsw_module, g_bpsw_tiers, g_bpsw_num_tiers,
                    _binary_ecpp_bpsw_fatbin_start,
                    (unsigned int)(_binary_ecpp_bpsw_fatbin_end - _binary_ecpp_bpsw_fatbin_start),
                    bpsw_ptx_source, "BPSW") != 0) {
        cu_cuModuleUnload(g_cornacchia_module);
        g_cornacchia_module = nullptr;
        cu_cuModuleUnload(g_tonelli_module);
        g_tonelli_module = nullptr;
        cu_cuCtxDestroy(g_context);
        g_context = nullptr;
        return -1;
    }

    /* Load EC Point Multiplication (CUBIN → PTX fallback) */
    if (load_module(&g_ec_module, g_ec_tiers, g_ec_num_tiers,
                    _binary_ecpp_ec_fatbin_start,
                    (unsigned int)(_binary_ecpp_ec_fatbin_end - _binary_ecpp_ec_fatbin_start),
                    ec_ptx_source, "EC Point Multiply") != 0) {
        cu_cuModuleUnload(g_bpsw_module);
        g_bpsw_module = nullptr;
        cu_cuModuleUnload(g_cornacchia_module);
        g_cornacchia_module = nullptr;
        cu_cuModuleUnload(g_tonelli_module);
        g_tonelli_module = nullptr;
        cu_cuCtxDestroy(g_context);
        g_context = nullptr;
        return -1;
    }

    fprintf(stderr, "ECPP GPU: Initialized — %s, %llu MB, %d tiers (Tonelli + Cornacchia + BPSW + EC)\n",
            g_device_name, (unsigned long long)(g_device_memory / (1024*1024)),
            g_tonelli_num_tiers);

    g_initialized = 1;
    return 0;
}

void ecpp_gpu_cleanup(void)
{
    if (!g_initialized) return;

    if (g_tonelli_module) {
        cu_cuModuleUnload(g_tonelli_module);
        g_tonelli_module = nullptr;
    }
    for (int i = 0; i < g_tonelli_num_tiers; i++)
        g_tonelli_tiers[i].kernel = nullptr;

    if (g_cornacchia_module) {
        cu_cuModuleUnload(g_cornacchia_module);
        g_cornacchia_module = nullptr;
    }
    for (int i = 0; i < g_cornacchia_num_tiers; i++)
        g_cornacchia_tiers[i].kernel = nullptr;

    if (g_bpsw_module) {
        cu_cuModuleUnload(g_bpsw_module);
        g_bpsw_module = nullptr;
    }
    for (int i = 0; i < g_bpsw_num_tiers; i++)
        g_bpsw_tiers[i].kernel = nullptr;

    if (g_ec_module) {
        cu_cuModuleUnload(g_ec_module);
        g_ec_module = nullptr;
    }
    for (int i = 0; i < g_ec_num_tiers; i++)
        g_ec_tiers[i].kernel = nullptr;

    if (g_context) {
        cu_cuCtxDestroy(g_context);
        g_context = nullptr;
    }

    g_initialized = 0;
}

int ecpp_gpu_is_available(void) { return g_initialized; }
const char* ecpp_gpu_device_name(void) { return g_device_name; }
uint64_t ecpp_gpu_device_memory(void) { return g_device_memory; }

/* =========================================================================
 * Helper: select tier by bit width from a tier table
 * ========================================================================= */

static KernelTierInfo* select_tier(KernelTierInfo *tiers, int num_tiers, int bits)
{
    for (int i = 0; i < num_tiers; i++)
        if (tiers[i].bits >= bits)
            return &tiers[i];
    return &tiers[num_tiers - 1];
}

/* =========================================================================
 * Batch Tonelli-Shanks
 * ========================================================================= */

int ecpp_gpu_tonelli_batch(
    uint32_t *h_roots,
    uint8_t  *h_success,
    const uint32_t *h_params,
    uint32_t e_val,
    const uint32_t *h_a,
    uint32_t count,
    int bits)
{
    if (!g_initialized) return -1;
    if (count == 0) return 0;

    /* Ensure our CUDA context is current on the calling thread.
     * Required when the DLL is loaded from a multi-threaded host (e.g.
     * Freycoin node) where init and usage may happen on different threads. */
    cu_cuCtxSetCurrent(g_context);

    KernelTierInfo* tier = select_tier(g_tonelli_tiers, g_tonelli_num_tiers, bits);
    int input_limbs = (bits + 31) / 32;
    int tier_limbs = tier->bits / 32;

    CUresult res;
    CUdeviceptr d_params = 0, d_a = 0, d_roots = 0, d_success = 0;

    size_t params_size  = (size_t)3 * tier_limbs * sizeof(uint32_t);
    size_t a_size       = (size_t)count * tier_limbs * sizeof(uint32_t);
    size_t roots_size   = (size_t)count * tier_limbs * sizeof(uint32_t);
    size_t success_size = (size_t)count * sizeof(uint8_t);

    /* Allocate device memory */
    res = cu_cuMemAlloc(&d_params, params_size);
    if (res != CUDA_SUCCESS) return -1;
    res = cu_cuMemAlloc(&d_a, a_size);
    if (res != CUDA_SUCCESS) { cu_cuMemFree(d_params); return -1; }
    res = cu_cuMemAlloc(&d_roots, roots_size);
    if (res != CUDA_SUCCESS) { cu_cuMemFree(d_params); cu_cuMemFree(d_a); return -1; }
    res = cu_cuMemAlloc(&d_success, success_size);
    if (res != CUDA_SUCCESS) { cu_cuMemFree(d_params); cu_cuMemFree(d_a); cu_cuMemFree(d_roots); return -1; }

    /* Upload params with zero-padding if input limbs < tier limbs */
    if (input_limbs < tier_limbs) {
        uint32_t* padded = (uint32_t*)calloc(3 * tier_limbs, sizeof(uint32_t));
        if (!padded) goto cleanup_fail;
        for (int j = 0; j < 3; j++)
            memcpy(&padded[j * tier_limbs], &h_params[j * input_limbs],
                   input_limbs * sizeof(uint32_t));
        cu_cuMemcpyHtoD(d_params, padded, params_size);
        free(padded);

        padded = (uint32_t*)calloc((size_t)count * tier_limbs, sizeof(uint32_t));
        if (!padded) goto cleanup_fail;
        for (uint32_t i = 0; i < count; i++)
            memcpy(&padded[i * tier_limbs], &h_a[i * input_limbs],
                   input_limbs * sizeof(uint32_t));
        cu_cuMemcpyHtoD(d_a, padded, a_size);
        free(padded);
    } else {
        cu_cuMemcpyHtoD(d_params, h_params, params_size);
        cu_cuMemcpyHtoD(d_a, h_a, a_size);
    }

    /* Launch kernel */
    {
        unsigned int threads_needed = count * tier->tpi;
        unsigned int grid_x = (threads_needed + ECPP_BLOCK_SIZE - 1) / ECPP_BLOCK_SIZE;

        void* params_arr[] = {
            &d_params, &e_val, &d_a, &d_roots, &d_success, &count
        };

        res = cu_cuLaunchKernel(tier->kernel,
                                  grid_x, 1, 1,
                                  ECPP_BLOCK_SIZE, 1, 1,
                                  0, nullptr, params_arr, nullptr);
        if (res != CUDA_SUCCESS) {
            fprintf(stderr, "ECPP GPU: Tonelli kernel launch failed for %d-bit tier (error %d)\n",
                    tier->bits, res);
            goto cleanup_fail;
        }
    }

    res = cu_cuCtxSynchronize();
    if (res != CUDA_SUCCESS) {
        fprintf(stderr, "ECPP GPU: Synchronize failed (error %d)\n", res);
        goto cleanup_fail;
    }

    if (input_limbs < tier_limbs) {
        uint32_t* padded_roots = (uint32_t*)malloc(roots_size);
        if (!padded_roots) goto cleanup_fail;
        cu_cuMemcpyDtoH(padded_roots, d_roots, roots_size);
        for (uint32_t i = 0; i < count; i++)
            memcpy(&h_roots[i * input_limbs], &padded_roots[i * tier_limbs],
                   input_limbs * sizeof(uint32_t));
        free(padded_roots);
    } else {
        cu_cuMemcpyDtoH(h_roots, d_roots, roots_size);
    }
    cu_cuMemcpyDtoH(h_success, d_success, success_size);

    cu_cuMemFree(d_params);
    cu_cuMemFree(d_a);
    cu_cuMemFree(d_roots);
    cu_cuMemFree(d_success);
    return 0;

cleanup_fail:
    cu_cuMemFree(d_params);
    cu_cuMemFree(d_a);
    cu_cuMemFree(d_roots);
    cu_cuMemFree(d_success);
    return -1;
}

/* =========================================================================
 * Batch Cornacchia
 * ========================================================================= */

int ecpp_gpu_cornacchia_batch(
    uint32_t *h_t,
    uint32_t *h_v,
    uint8_t  *h_success,
    const uint32_t *h_p,
    const uint32_t *h_sqrt_d,
    const int32_t  *h_d,
    uint32_t count,
    int bits)
{
    if (!g_initialized) return -1;
    if (count == 0) return 0;

    cu_cuCtxSetCurrent(g_context);

    /* Select tier with +3 bits headroom for 4p intermediate values */
    KernelTierInfo* tier = select_tier(g_cornacchia_tiers, g_cornacchia_num_tiers, bits + 3);
    int input_limbs = (bits + 31) / 32;
    int tier_limbs = tier->bits / 32;

    CUresult res;
    CUdeviceptr d_params = 0, d_sqrt_d = 0, d_d = 0;
    CUdeviceptr d_t = 0, d_v = 0, d_success = 0;

    size_t params_size  = (size_t)tier_limbs * sizeof(uint32_t);
    size_t per_inst     = (size_t)count * tier_limbs * sizeof(uint32_t);
    size_t d_d_size     = (size_t)count * sizeof(int32_t);
    size_t success_size = (size_t)count * sizeof(uint8_t);

    /* Allocate device memory */
    res = cu_cuMemAlloc(&d_params, params_size);
    if (res != CUDA_SUCCESS) return -1;
    res = cu_cuMemAlloc(&d_sqrt_d, per_inst);
    if (res != CUDA_SUCCESS) { cu_cuMemFree(d_params); return -1; }
    res = cu_cuMemAlloc(&d_d, d_d_size);
    if (res != CUDA_SUCCESS) { cu_cuMemFree(d_params); cu_cuMemFree(d_sqrt_d); return -1; }
    res = cu_cuMemAlloc(&d_t, per_inst);
    if (res != CUDA_SUCCESS) { cu_cuMemFree(d_params); cu_cuMemFree(d_sqrt_d); cu_cuMemFree(d_d); return -1; }
    res = cu_cuMemAlloc(&d_v, per_inst);
    if (res != CUDA_SUCCESS) { cu_cuMemFree(d_params); cu_cuMemFree(d_sqrt_d); cu_cuMemFree(d_d); cu_cuMemFree(d_t); return -1; }
    res = cu_cuMemAlloc(&d_success, success_size);
    if (res != CUDA_SUCCESS) { cu_cuMemFree(d_params); cu_cuMemFree(d_sqrt_d); cu_cuMemFree(d_d); cu_cuMemFree(d_t); cu_cuMemFree(d_v); return -1; }

    /* Upload params with zero-padding */
    if (input_limbs < tier_limbs) {
        uint32_t* padded = (uint32_t*)calloc(tier_limbs, sizeof(uint32_t));
        if (!padded) goto cleanup_fail;
        memcpy(padded, h_p, input_limbs * sizeof(uint32_t));
        cu_cuMemcpyHtoD(d_params, padded, params_size);
        free(padded);

        /* Pad sqrt_d values */
        padded = (uint32_t*)calloc((size_t)count * tier_limbs, sizeof(uint32_t));
        if (!padded) goto cleanup_fail;
        for (uint32_t i = 0; i < count; i++)
            memcpy(&padded[i * tier_limbs], &h_sqrt_d[i * input_limbs],
                   input_limbs * sizeof(uint32_t));
        cu_cuMemcpyHtoD(d_sqrt_d, padded, per_inst);
        free(padded);
    } else {
        cu_cuMemcpyHtoD(d_params, h_p, params_size);
        cu_cuMemcpyHtoD(d_sqrt_d, h_sqrt_d, per_inst);
    }

    /* Upload discriminants (no padding needed) */
    cu_cuMemcpyHtoD(d_d, h_d, d_d_size);

    /* Launch kernel */
    {
        unsigned int threads_needed = count * tier->tpi;
        unsigned int grid_x = (threads_needed + ECPP_BLOCK_SIZE - 1) / ECPP_BLOCK_SIZE;

        void* params_arr[] = {
            &d_params, &d_sqrt_d, &d_d, &d_t, &d_v, &d_success, &count
        };

        res = cu_cuLaunchKernel(tier->kernel,
                                  grid_x, 1, 1,
                                  ECPP_BLOCK_SIZE, 1, 1,
                                  0, nullptr, params_arr, nullptr);
        if (res != CUDA_SUCCESS) {
            fprintf(stderr, "ECPP GPU: Cornacchia kernel launch failed for %d-bit tier (error %d)\n",
                    tier->bits, res);
            goto cleanup_fail;
        }
    }

    res = cu_cuCtxSynchronize();
    if (res != CUDA_SUCCESS) {
        fprintf(stderr, "ECPP GPU: Synchronize failed (error %d)\n", res);
        goto cleanup_fail;
    }

    /* Download results with un-padding */
    if (input_limbs < tier_limbs) {
        uint32_t* padded = (uint32_t*)malloc(per_inst);
        if (!padded) goto cleanup_fail;

        cu_cuMemcpyDtoH(padded, d_t, per_inst);
        for (uint32_t i = 0; i < count; i++)
            memcpy(&h_t[i * input_limbs], &padded[i * tier_limbs],
                   input_limbs * sizeof(uint32_t));

        cu_cuMemcpyDtoH(padded, d_v, per_inst);
        for (uint32_t i = 0; i < count; i++)
            memcpy(&h_v[i * input_limbs], &padded[i * tier_limbs],
                   input_limbs * sizeof(uint32_t));

        free(padded);
    } else {
        cu_cuMemcpyDtoH(h_t, d_t, per_inst);
        cu_cuMemcpyDtoH(h_v, d_v, per_inst);
    }
    cu_cuMemcpyDtoH(h_success, d_success, success_size);

    cu_cuMemFree(d_params);
    cu_cuMemFree(d_sqrt_d);
    cu_cuMemFree(d_d);
    cu_cuMemFree(d_t);
    cu_cuMemFree(d_v);
    cu_cuMemFree(d_success);
    return 0;

cleanup_fail:
    cu_cuMemFree(d_params);
    cu_cuMemFree(d_sqrt_d);
    cu_cuMemFree(d_d);
    cu_cuMemFree(d_t);
    cu_cuMemFree(d_v);
    cu_cuMemFree(d_success);
    return -1;
}

/* =========================================================================
 * Batch BPSW (Strong Miller-Rabin base 2)
 * ========================================================================= */

int ecpp_gpu_bpsw_batch(
    uint8_t  *h_results,
    const uint32_t *h_n,
    uint32_t count,
    int bits)
{
    if (!g_initialized) return -1;
    if (count == 0) return 0;

    cu_cuCtxSetCurrent(g_context);

    KernelTierInfo* tier = select_tier(g_bpsw_tiers, g_bpsw_num_tiers, bits);
    int input_limbs = (bits + 31) / 32;
    int tier_limbs = tier->bits / 32;

    CUresult res;
    CUdeviceptr d_n = 0, d_results = 0;

    size_t n_size = (size_t)count * tier_limbs * sizeof(uint32_t);
    size_t r_size = (size_t)count * sizeof(uint8_t);

    res = cu_cuMemAlloc(&d_n, n_size);
    if (res != CUDA_SUCCESS) return -1;
    res = cu_cuMemAlloc(&d_results, r_size);
    if (res != CUDA_SUCCESS) { cu_cuMemFree(d_n); return -1; }

    /* Upload with zero-padding */
    if (input_limbs < tier_limbs) {
        uint32_t* padded = (uint32_t*)calloc((size_t)count * tier_limbs, sizeof(uint32_t));
        if (!padded) { cu_cuMemFree(d_n); cu_cuMemFree(d_results); return -1; }
        for (uint32_t i = 0; i < count; i++)
            memcpy(&padded[i * tier_limbs], &h_n[i * input_limbs],
                   input_limbs * sizeof(uint32_t));
        cu_cuMemcpyHtoD(d_n, padded, n_size);
        free(padded);
    } else {
        cu_cuMemcpyHtoD(d_n, h_n, n_size);
    }

    /* Launch kernel */
    {
        unsigned int threads_needed = count * tier->tpi;
        unsigned int grid_x = (threads_needed + ECPP_BLOCK_SIZE - 1) / ECPP_BLOCK_SIZE;

        void* params_arr[] = { &d_n, &d_results, &count };

        res = cu_cuLaunchKernel(tier->kernel,
                                  grid_x, 1, 1,
                                  ECPP_BLOCK_SIZE, 1, 1,
                                  0, nullptr, params_arr, nullptr);
        if (res != CUDA_SUCCESS) {
            fprintf(stderr, "ECPP GPU: BPSW kernel launch failed for %d-bit tier (error %d)\n",
                    tier->bits, res);
            cu_cuMemFree(d_n); cu_cuMemFree(d_results);
            return -1;
        }
    }

    res = cu_cuCtxSynchronize();
    if (res != CUDA_SUCCESS) {
        fprintf(stderr, "ECPP GPU: Synchronize failed (error %d)\n", res);
        cu_cuMemFree(d_n); cu_cuMemFree(d_results);
        return -1;
    }

    cu_cuMemcpyDtoH(h_results, d_results, r_size);

    cu_cuMemFree(d_n);
    cu_cuMemFree(d_results);
    return 0;
}

/* =========================================================================
 * Batch EC Point Multiplication
 * ========================================================================= */

int ecpp_gpu_ec_multiply_batch(
    uint32_t *h_result_x,
    uint32_t *h_result_y,
    uint8_t  *h_is_infinity,
    const uint32_t *h_params,
    const uint32_t *h_points,
    const uint32_t *h_scalars,
    uint32_t count,
    int bits)
{
    if (!g_initialized) return -1;
    if (count == 0) return 0;

    cu_cuCtxSetCurrent(g_context);

    KernelTierInfo* tier = select_tier(g_ec_tiers, g_ec_num_tiers, bits);
    int input_limbs = (bits + 31) / 32;
    int tier_limbs = tier->bits / 32;

    CUresult res;
    CUdeviceptr d_params = 0, d_points = 0, d_scalars = 0;
    CUdeviceptr d_rx = 0, d_ry = 0, d_inf = 0;

    size_t params_sz = (size_t)2 * tier_limbs * sizeof(uint32_t);
    size_t pts_sz    = (size_t)count * 2 * tier_limbs * sizeof(uint32_t);
    size_t scl_sz    = (size_t)count * tier_limbs * sizeof(uint32_t);
    size_t out_sz    = (size_t)count * tier_limbs * sizeof(uint32_t);
    size_t inf_sz    = (size_t)count * sizeof(uint8_t);

    /* Allocate device memory */
    res = cu_cuMemAlloc(&d_params, params_sz);
    if (res != CUDA_SUCCESS) return -1;
    res = cu_cuMemAlloc(&d_points, pts_sz);
    if (res != CUDA_SUCCESS) { cu_cuMemFree(d_params); return -1; }
    res = cu_cuMemAlloc(&d_scalars, scl_sz);
    if (res != CUDA_SUCCESS) { cu_cuMemFree(d_params); cu_cuMemFree(d_points); return -1; }
    res = cu_cuMemAlloc(&d_rx, out_sz);
    if (res != CUDA_SUCCESS) { cu_cuMemFree(d_params); cu_cuMemFree(d_points); cu_cuMemFree(d_scalars); return -1; }
    res = cu_cuMemAlloc(&d_ry, out_sz);
    if (res != CUDA_SUCCESS) { cu_cuMemFree(d_params); cu_cuMemFree(d_points); cu_cuMemFree(d_scalars); cu_cuMemFree(d_rx); return -1; }
    res = cu_cuMemAlloc(&d_inf, inf_sz);
    if (res != CUDA_SUCCESS) { cu_cuMemFree(d_params); cu_cuMemFree(d_points); cu_cuMemFree(d_scalars); cu_cuMemFree(d_rx); cu_cuMemFree(d_ry); return -1; }

    /* Upload with zero-padding */
    if (input_limbs < tier_limbs) {
        /* Params: [p | a] */
        uint32_t* pad = (uint32_t*)calloc(2 * tier_limbs, sizeof(uint32_t));
        if (!pad) goto cleanup_fail;
        memcpy(&pad[0], &h_params[0], input_limbs * sizeof(uint32_t));
        memcpy(&pad[tier_limbs], &h_params[input_limbs], input_limbs * sizeof(uint32_t));
        cu_cuMemcpyHtoD(d_params, pad, params_sz);
        free(pad);

        /* Points: [Px | Py] per instance */
        pad = (uint32_t*)calloc((size_t)count * 2 * tier_limbs, sizeof(uint32_t));
        if (!pad) goto cleanup_fail;
        for (uint32_t i = 0; i < count; i++) {
            memcpy(&pad[i * 2 * tier_limbs], &h_points[i * 2 * input_limbs],
                   input_limbs * sizeof(uint32_t));
            memcpy(&pad[i * 2 * tier_limbs + tier_limbs],
                   &h_points[i * 2 * input_limbs + input_limbs],
                   input_limbs * sizeof(uint32_t));
        }
        cu_cuMemcpyHtoD(d_points, pad, pts_sz);
        free(pad);

        /* Scalars */
        pad = (uint32_t*)calloc((size_t)count * tier_limbs, sizeof(uint32_t));
        if (!pad) goto cleanup_fail;
        for (uint32_t i = 0; i < count; i++)
            memcpy(&pad[i * tier_limbs], &h_scalars[i * input_limbs],
                   input_limbs * sizeof(uint32_t));
        cu_cuMemcpyHtoD(d_scalars, pad, scl_sz);
        free(pad);
    } else {
        cu_cuMemcpyHtoD(d_params, h_params, params_sz);
        cu_cuMemcpyHtoD(d_points, h_points, pts_sz);
        cu_cuMemcpyHtoD(d_scalars, h_scalars, scl_sz);
    }

    /* Launch kernel */
    {
        unsigned int threads_needed = count * tier->tpi;
        unsigned int grid_x = (threads_needed + ECPP_BLOCK_SIZE - 1) / ECPP_BLOCK_SIZE;

        void* params_arr[] = {
            &d_params, &d_points, &d_scalars, &d_rx, &d_ry, &d_inf, &count
        };

        res = cu_cuLaunchKernel(tier->kernel,
                                  grid_x, 1, 1,
                                  ECPP_BLOCK_SIZE, 1, 1,
                                  0, nullptr, params_arr, nullptr);
        if (res != CUDA_SUCCESS) {
            fprintf(stderr, "ECPP GPU: EC kernel launch failed for %d-bit tier (error %d)\n",
                    tier->bits, res);
            goto cleanup_fail;
        }
    }

    res = cu_cuCtxSynchronize();
    if (res != CUDA_SUCCESS) {
        fprintf(stderr, "ECPP GPU: Synchronize failed (error %d)\n", res);
        goto cleanup_fail;
    }

    /* Download results */
    if (input_limbs < tier_limbs) {
        uint32_t* pad = (uint32_t*)malloc(out_sz);
        if (!pad) goto cleanup_fail;
        cu_cuMemcpyDtoH(pad, d_rx, out_sz);
        for (uint32_t i = 0; i < count; i++)
            memcpy(&h_result_x[i * input_limbs], &pad[i * tier_limbs],
                   input_limbs * sizeof(uint32_t));
        cu_cuMemcpyDtoH(pad, d_ry, out_sz);
        for (uint32_t i = 0; i < count; i++)
            memcpy(&h_result_y[i * input_limbs], &pad[i * tier_limbs],
                   input_limbs * sizeof(uint32_t));
        free(pad);
    } else {
        cu_cuMemcpyDtoH(h_result_x, d_rx, out_sz);
        cu_cuMemcpyDtoH(h_result_y, d_ry, out_sz);
    }
    cu_cuMemcpyDtoH(h_is_infinity, d_inf, inf_sz);

    cu_cuMemFree(d_params);
    cu_cuMemFree(d_points);
    cu_cuMemFree(d_scalars);
    cu_cuMemFree(d_rx);
    cu_cuMemFree(d_ry);
    cu_cuMemFree(d_inf);
    return 0;

cleanup_fail:
    cu_cuMemFree(d_params);
    cu_cuMemFree(d_points);
    cu_cuMemFree(d_scalars);
    cu_cuMemFree(d_rx);
    cu_cuMemFree(d_ry);
    cu_cuMemFree(d_inf);
    return -1;
}

/* Polynomial powmod — not used for nextprime (only ECPP Phase 2).
   Stub provided to satisfy the linker for ecpp_gpu_shim.c. */
int ecpp_gpu_poly_powmod_batch(
    uint32_t       * /*h_results*/,
    const uint32_t * /*h_f*/,
    const uint32_t * /*h_e*/,
    const uint32_t * /*h_p*/,
    const uint64_t * /*h_a*/,
    uint32_t        /*H*/,
    int             /*bits*/,
    uint32_t        /*e_bits*/,
    uint32_t        /*count*/)
{
    return -1;
}
