#ifndef FREYCOIN_CHAINPARAMSSEEDS_H
#define FREYCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the Freycoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
    0x01,0x04,0x8a,0xc5,0x82,0xdd,0x7a,0xee,
    0x01,0x04,0x9f,0xdf,0xe7,0x4b,0x7a,0xee,
};

static const uint8_t chainparams_seed_test[] = {
    0x01,0x04,0x8a,0xc5,0x82,0xdd,0x7a,0xf1,
};
#endif // FREYCOIN_CHAINPARAMSSEEDS_H
